import type { Lang } from "./i18n";

/**
 * Teks antarmuka bersama.
 *
 * Prosa khusus tiap laboratorium tidak ditaruh di sini melainkan di
 * berkas laboratoriumnya masing-masing, supaya kalimat penjelas tetap
 * berdampingan dengan perhitungan yang dijelaskannya.
 */
export const S = {
  id: {
    /* kepala dan kaki halaman */
    tagline: "laboratorium hidraulika interaktif",
    headerMeta: "berkas gambar · satuan SI · purwarupa",
    langLabel: "bahasa",
    footer1:
      "HidroLab adalah purwarupa. Seluruh perhitungan berjalan di peramban dan tidak ada data yang dikirim keluar. Model diturunkan dari persamaan baku teknik hidro.",
    footer2:
      "Hasil pada lembar-lembar ini ditujukan untuk membangun pemahaman, bukan menggantikan perhitungan desain yang terjamin mutunya. Setiap keluaran harus diperiksa secara independen sebelum dipakai untuk desain, penilaian keselamatan, atau pengajuan ke regulator.",
    skip: "Lompat ke konten",

    /* beranda */
    homeTitle: "Berkas lembar gambar yang bisa dihitung ulang.",
    homeLead:
      "Setiap lembar di sini adalah gambar teknik yang hidup. Geser satu masukan, dan seluruh isinya dihitung ulang: profil muka air, garis energi, dimensi, sampai kop di bawah gambar. Tidak ada tabel jadi yang disalin, tidak ada gambar yang ditempel.",
    sheetIndex: "daftar lembar",
    colSheet: "Lembar",
    colTitle: "Judul",
    colSubject: "Pokok bahasan",
    colQuestion: "Pertanyaan yang dijawab",
    colStatus: "Status",
    statusReady: "terbit",
    statusPlanned: "rencana",
    indexNote:
      "Lembar bertanda terbit sudah berjalan penuh. Sisanya memperlihatkan bagaimana berkas ini tumbuh: menambah satu lembar berarti menambah satu model perhitungan dan satu penggambar, sementara kerangka, kop, dan tata letaknya sudah dipakai bersama.",
    methodHeading: "cara lembar ini dibuat",
    method1:
      "Angka-angkanya diselesaikan sendiri, bukan diambil dari tabel. Kedalaman konjugat memakai persamaan Belanger; faktor gesekan memakai Colebrook-White yang implisit, diselesaikan dengan iterasi Newton-Raphson; kedalaman normal memakai Manning yang dibalik dengan metode bagi dua.",
    method2:
      "Gambarnya digambar garis demi garis, tanpa pustaka grafik siap pakai. Itu sebabnya penampang, kurva log-log, dan arsiran air bisa mengikuti konvensi gambar teknik alih-alih mengikuti bentuk bawaan sebuah pustaka.",
    rulesHeading: "aturan yang dipegang",
    ruleBold: "Garis tebal",
    ruleBoldV: "Geometri nyata: dasar, dinding, muka air",
    ruleThin: "Garis tipis",
    ruleThinV: "Yang membicarakan benda: dimensi, penunjuk, arsiran",
    ruleDash: "Garis putus",
    ruleDashV: "Garis energi, dan hal yang tak terlihat langsung",
    ruleDot: "Titik rapat",
    ruleDotV: "Di luar jangkauan rumus — gambar mengaku tidak tahu",
    ruleBlue: "Biru",
    ruleBlueV: "Selalu air. Tidak pernah dipakai untuk hal lain",
    ruleRed: "Merah bata",
    ruleRedV: "Selalu energi",
    rulePurple: "Ungu",
    rulePurpleV: "Selalu kondisi kritis",

    /* kerangka lembar */
    backToIndex: "← daftar lembar",
    sheetWord: "lembar",
    blkInput: "masukan",
    blkResult: "hasil",
    blkCondition: "kondisi",
    blkNotice: "yang perlu diperhatikan",
    blkBasis: "dasar perhitungan",
    blkRefs: "rujukan",
    presetExample: "kondisi contoh",
    presetView: "tampilan",

    /* kop gambar */
    tbSimulation: "simulasi",
    tbSheet: "lembar",
    tbRev: "rev",
    tbScale: "skala",
    tbUnit: "satuan",
    tbRegime: "regime",
    tbAxis: "sumbu",
    tbSlope: "kemiringan",

    /* tabel */
    thSym: "Sim",
    thQuantity: "Besaran",
    thValue: "Nilai",
    thComputed: "Besaran terhitung",
  },

  en: {
    tagline: "interactive hydraulics laboratory",
    headerMeta: "drawing set · SI units · prototype",
    langLabel: "language",
    footer1:
      "HidroLab is a prototype. Every calculation runs in your browser and no data leaves your device. The models are derived from standard hydraulic engineering equations.",
    footer2:
      "Results on these sheets are meant for building understanding, not for replacing quality-assured design calculations. Every output must be checked independently before it is used for design, safety assessment, or regulatory submission.",
    skip: "Skip to content",

    homeTitle: "A drawing set that recalculates itself.",
    homeLead:
      "Every sheet here is a living engineering drawing. Move one input and the whole thing is recomputed: water surface profile, energy line, dimensions, right down to the title block beneath the drawing. No pasted tables, no static images.",
    sheetIndex: "sheet index",
    colSheet: "Sheet",
    colTitle: "Title",
    colSubject: "Subject",
    colQuestion: "Question it answers",
    colStatus: "Status",
    statusReady: "issued",
    statusPlanned: "planned",
    indexNote:
      "Sheets marked issued are fully working. The rest show how this set grows: adding a sheet means adding one calculation model and one renderer, while the framework, title block, and layout are already shared.",
    methodHeading: "how these sheets are made",
    method1:
      "The numbers are solved here, not looked up. Conjugate depth uses the Bélanger equation; the friction factor uses the implicit Colebrook-White equation solved by Newton-Raphson iteration; normal depth inverts Manning's equation using bisection.",
    method2:
      "The drawings are drawn line by line, with no charting library. That is why the cross sections, log-log curves, and water hatching can follow engineering drawing conventions instead of a library's built-in shapes.",
    rulesHeading: "rules held throughout",
    ruleBold: "Thick line",
    ruleBoldV: "Real geometry: bed, walls, water surface",
    ruleThin: "Thin line",
    ruleThinV: "What talks about the object: dimensions, leaders, hatching",
    ruleDash: "Dashed line",
    ruleDashV: "Energy line, and anything not directly visible",
    ruleDot: "Fine dots",
    ruleDotV: "Beyond the reach of the equation — the drawing admits it",
    ruleBlue: "Blue",
    ruleBlueV: "Always water. Never used for anything else",
    ruleRed: "Brick red",
    ruleRedV: "Always energy",
    rulePurple: "Violet",
    rulePurpleV: "Always the critical condition",

    backToIndex: "← sheet index",
    sheetWord: "sheet",
    blkInput: "input",
    blkResult: "results",
    blkCondition: "condition",
    blkNotice: "what to notice",
    blkBasis: "basis of calculation",
    blkRefs: "references",
    presetExample: "example conditions",
    presetView: "display",

    tbSimulation: "simulation",
    tbSheet: "sheet",
    tbRev: "rev",
    tbScale: "scale",
    tbUnit: "units",
    tbRegime: "regime",
    tbAxis: "axes",
    tbSlope: "slope",

    thSym: "Sym",
    thQuantity: "Quantity",
    thValue: "Value",
    thComputed: "Computed quantity",
  },
} as const;

export type Strings = (typeof S)["id"];

export function str(lang: Lang): Strings {
  return S[lang] as Strings;
}

/* ------------------------------------------------------------------ *
 * Label di dalam gambar
 *
 * Dipisahkan dari teks antarmuka karena dipakai oleh fungsi penggambar,
 * yang berjalan di luar React dan hanya menerima kode bahasa.
 * ------------------------------------------------------------------ */

export const CANVAS = {
  id: {
    axDistance: "jarak sepanjang saluran, m",
    axDepth: "kedalaman, m",
    axEnergy: "energi spesifik E, m",
    axMomentum: "fungsi momentum M, m³/m",
    axDepthShort: "kedalaman y, m",
    axReynolds: "bilangan reynolds, Re",
    axGradient: "kemiringan hidrolik, S",
    axMeanVelocity: "kecepatan rata-rata, m/s",
    axYPlus: "jarak dari dinding, y⁺",
    axUPlus: "kecepatan, u⁺",
    axHydraulicRadius: "jari-jari hidrolik, m",
    axChezy: "koefisien chezy, m^0,5/s",
    axGrainSize: "ukuran butir tak berdimensi, D*",
    axShields: "tegangan geser tak berdimensi, θ",
    viscousLayer: "lapisan kental",
    bufferLayer: "lapisan penyangga",
    logLayer: "lapisan logaritmik",
    noLawHere: "tidak ada hukum sederhana di sini",
    grainMoves: "butir bergerak",
    grainRests: "butir diam",
    thresholdCurve: "ambang gerak",
    manningCurve: "manning",
    darcyCurve: "darcy",
    smoothWallCurve: "dinding licin",
    axRelConc: "kepekatan nisbi, c/ca",
    axHeight: "ketinggian di atas dasar, y/h",
    axGrainMm: "garis tengah butir, mm",
    axMeanVel: "kecepatan rata-rata, m/s",
    axOverflow: "laju limpah, m/h",
    axEfficiency: "bagian tertangkap",
    erosionCurve: "erosi",
    depositionCurve: "pengendapan",
    suspensionCurve: "melayang",
    transportZone: "terangkut",
    depositionZone: "mengendap",
    erosionZone: "tererosi",
    referenceHeight: "ketinggian acuan",
    idealBasin: "bak ideal",
    mixedBasin: "bak teraduk",
    axTimeHour: "waktu sejak hujan mulai, h",
    axFlowRate: "debit, m³/s",
    inflowCurve: "debit masuk",
    outflowCurve: "debit keluar",
    unitHydrograph: "hidrograf satuan",
    rainBurst: "hujan efektif",
    peakLabel: "puncak",
    crestLevel: "mercu pelimpah",
    freeboardLevel: "puncak bendungan",
    axSwimSpeed: "kecepatan arus, m/s",
    axEndurance: "lama bertahan, detik",
    axTrophic: "tingkat trofik",
    axEnergyFlow: "aliran energi, kJ/m²·y",
    axEffort: "upaya penangkapan",
    axYield: "hasil lestari, ton/y",
    axRecapture: "bertanda di tangkapan kedua",
    axPopulation: "taksiran populasi",
    axYear: "tahun",
    axFish: "populasi, ekor",
    sustainedZone: "jelajah",
    burstZone: "sentak",
    unableZone: "tidak mampu",
    msyPoint: "hasil lestari maksimum",
    overfishedZone: "penangkapan berlebih",
    thresholdPassage: "ambang kelestarian",
    extinctPath: "menuju punah",
    axHoriz: "jarak mendatar, m",
    axLevel: "elevasi, m",
    designNappe: "tirai pada tinggi rancangan",
    crestProfile: "muka mercu",
    upstreamPool: "genangan hulu",
    stilling: "kolam olak",
    noControl: "mercu tidak mengendalikan aliran",
    cavitation: "tekanan mercu di bawah ambang kavitasi",
    cycleLabel: "satu siklus",
    planView2: "tampak atas",
    nappeMeet: "tirai bertemu di tengah siklus",
    gateLeaf: "daun pintu",
    venaSection: "vena contracta",
    submergedGate: "pintu tenggelam",
    inletControl: "kendali sisi masuk",
    outletControl: "kendali sisi keluar",
    roadLevel: "permukaan jalan",
    barrelLabel: "gorong-gorong",
    pierLabel: "pilar",
    backwaterLabel: "pembendungan",
    scourLabel: "gerusan setempat",
    stoneLayer: "lapisan batu",
    poolLabel: "kolam",
    slotLabel: "celah tegak",
    baffleLabel: "sirip penahan",
    stepLabel: "undakan",
    restPool: "kolam istirahat",
    axFriction: "faktor gesekan darcy, f",
    axRoughness: "kekasaran relatif, ε/D",
    axHead: "tinggi energi H, m",
    axDischarge: "debit Q, m³/s",
    energyLine: "garis energi",
    supercritical: "superkritis",
    subcritical: "subkritis",
    jump: "loncatan",
    noJump: "tidak terbentuk loncatan",
    laminar: "laminar",
    criticalZone: "zona kritis",
    fullyRough: "turbulen penuh",
    smoothPipe: "pipa licin",
    pointOffChart: "titik operasi di luar diagram",
    branchSub: "cabang subkritis",
    branchSuper: "cabang superkritis",
    critical: "kritis",
    normal: "normal",
    section: "penampang melintang",
    minEnergy: "E min",
    ratingCurve: "kurva debit",
    notch: "ambang",
    profile: "profil muka air",
    control: "penampang kendali",
    belowRange: "di luar rentang",
    elevation: "elevasi, m",
    upstream: "hulu",
    downstream: "hilir",
    choked: "tersendat",
    planView: "tampak atas",
    slopeBreak: "patahan kemiringan",
    reachUp: "ruas hulu",
    reachDown: "ruas hilir",
    uniform: "seragam",
    energyGrade: "garis energi",
    waterGrade: "garis muka air",
    velocityHead: "tinggi kecepatan",
    datum: "datum",
    lateralInflow: "aliran masuk lateral",
    noInflow: "tanpa suku percepatan",
    momentumEqual: "momentum sama",
    axStation: "jarak dari mercu, m",
    axFromOrifice: "jarak dari bidang lubang, m",
    axAlongPipe: "jarak sepanjang pipa, m",
    projectile: "lintasan peluru",
    airPocket: "rongga udara",
    notAerated: "rongga tanpa udara",
    suction: "tirai tertarik ke mercu",
    freeNappe: "tirai luapan bebas",
    notSubmerged: "bibir atas lubang di atas muka air",
    drownedNappe: "tirai tenggelam, bukan luapan bebas",
    throat: "leher",
    gauging: "penampang ukur",
    submerged: "tenggelam",
    axTime: "waktu sejak penyuntikan, detik",
    axConc: "kepekatan di atas latar, mg/l",
    axVelocity: "kecepatan setempat, m/s",
    axRadius: "jarak dari sumbu pipa, m",
    venaContracta: "vena contracta",
    orifice: "lubang",
    jet: "pancaran",
    throatSection: "leher",
    pressureTap: "titik ukur tekanan",
    stagnation: "lubang stagnasi",
    staticPort: "lubang statik",
    meanVelocity: "kecepatan rata-rata",
    peak: "puncak",
    areaUnder: "luas kurva",
    pressureLine: "garis tinggi tekan",
    notVenturi: "bukan venturi: leher tidak lebih sempit dari pipa",
    throatNoControl: "leher tidak mengendalikan aliran, debit tidak dapat dihitung",
    powerLaw: "hukum pangkat",
    wider: "sebaran lebih besar",
    steadyRate: "laju tetap",
    aboveChart: "di atas bidang",
    noProfile: "profil tidak dapat dihitung",
    noNormalDepth: "tidak ada kedalaman normal",
    rapidlyVaried: "aliran berubah cepat",
    profileEnds: "profil berakhir di sini",
    collector: "saluran pengumpul",
    influenceEnd: "pengaruh tinggal 1%",
    structure: "bangunan",
    structureDrowned: "bangunan tenggelam, tidak membendung",
    tailwater: "muka air hilir",
    drowned: "loncatan tenggelam",
    crest: "mercu",
    /* keluarga G: air tanah, rembesan, geoteknik */
    axSection: "jarak mendatar, m",
    millionCubic: "juta m³",
    noRunoff: "hujan ini tidak menghasilkan limpasan",
    wallRoughness: "kekasaran dinding",
    phreaticLine: "garis freatik",
    toeDrain: "drainase kaki",
    embankment: "tubuh bendungan",
    imperviousLabel: "lapisan kedap",
    seepageFace: "muka rembesan",
    wellLabel: "sumur",
    drawdownCone: "kerucut penurunan",
    staticLevel: "muka air mula-mula",
    pumpingLevel: "muka air saat dipompa",
    aquiferLabel: "akuifer",
    confiningLabel: "lapisan penutup",
    halfDrawdown: "separuh penurunan",
    influenceRadius: "jari-jari pengaruh",
    axWellRadius: "jarak dari sumbu sumur, m",
    axDrawdown: "penurunan muka air, m",
    axDay: "waktu, d",
    axWaterTable: "muka air tanah, m",
    axRecharge: "imbuhan, mm/d",
    rechargeCurve: "imbuhan",
    headCurve: "muka air tanah",
    meanLevel: "aras rata-rata",
    lagLabel: "tundaan puncak",
    upliftLabel: "tekanan angkat",
    resultantLabel: "resultan",
    middleThird: "sepertiga tengah",
    heelLabel: "tumit",
    toeLabelDam: "ujung kaki",
    drainLine: "garis tirisan",
    baseStress: "tegangan dasar",
    axGrainLog: "garis tengah butiran, mm",
    axPassing: "lolos ayakan, %",
    baseSoil: "tanah yang dilindungi",
    filterSoil: "filter",
    filterWindow: "jendela filter",
    retainLimit: "batas menahan",
    drainLimit: "batas mengalirkan",
    axSeepGradient: "gradien hidraulik, i",
    axSeepVelocity: "kecepatan semu, m/s",
    darcyLine: "hukum darcy",
    inertialLine: "batas inersia",
    rockfillLabel: "urugan batu",
    axHour: "jam dalam sehari, h",
    sleepPressure: "tekanan tidur S",
    upperThreshold: "ambang atas",
    lowerThreshold: "ambang bawah",
    asleepLabel: "tidur",
    awakeLabel: "terjaga",
    lyingAwake: "berbaring",
    freeRun: "daur bebas",
  },
  en: {
    axDistance: "distance along channel, m",
    axDepth: "depth, m",
    axEnergy: "specific energy E, m",
    axMomentum: "momentum function M, m³/m",
    axDepthShort: "depth y, m",
    axReynolds: "reynolds number, Re",
    axGradient: "hydraulic gradient, S",
    axMeanVelocity: "mean velocity, m/s",
    axYPlus: "distance from the wall, y⁺",
    axUPlus: "velocity, u⁺",
    axHydraulicRadius: "hydraulic radius, m",
    axChezy: "chezy coefficient, m^0.5/s",
    axGrainSize: "dimensionless grain size, D*",
    axShields: "dimensionless shear stress, θ",
    viscousLayer: "viscous layer",
    bufferLayer: "buffer layer",
    logLayer: "logarithmic layer",
    noLawHere: "no simple law holds here",
    grainMoves: "grain moves",
    grainRests: "grain at rest",
    thresholdCurve: "threshold of motion",
    manningCurve: "manning",
    darcyCurve: "darcy",
    smoothWallCurve: "smooth wall",
    axRelConc: "relative concentration, c/ca",
    axHeight: "height above the bed, y/h",
    axGrainMm: "grain diameter, mm",
    axMeanVel: "mean velocity, m/s",
    axOverflow: "overflow rate, m/h",
    axEfficiency: "fraction captured",
    erosionCurve: "erosion",
    depositionCurve: "deposition",
    suspensionCurve: "suspension",
    transportZone: "transported",
    depositionZone: "deposition",
    erosionZone: "erosion",
    referenceHeight: "reference height",
    idealBasin: "ideal basin",
    mixedBasin: "mixed basin",
    axTimeHour: "time since rain began, h",
    axFlowRate: "discharge, m³/s",
    inflowCurve: "inflow",
    outflowCurve: "outflow",
    unitHydrograph: "unit hydrograph",
    rainBurst: "effective rain",
    peakLabel: "peak",
    crestLevel: "spillway crest",
    freeboardLevel: "dam crest",
    axSwimSpeed: "current velocity, m/s",
    axEndurance: "endurance, s",
    axTrophic: "trophic level",
    axEnergyFlow: "energy flow, kJ/m²·y",
    axEffort: "fishing effort",
    axYield: "sustainable yield, t/y",
    axRecapture: "marked in the second catch",
    axPopulation: "population estimate",
    axYear: "year",
    axFish: "population, individuals",
    sustainedZone: "sustained",
    burstZone: "burst",
    unableZone: "unable",
    msyPoint: "maximum sustainable yield",
    overfishedZone: "overfished",
    thresholdPassage: "sustainability threshold",
    extinctPath: "heading to extinction",
    axHoriz: "horizontal distance, m",
    axLevel: "elevation, m",
    designNappe: "nappe at the design head",
    crestProfile: "crest profile",
    upstreamPool: "upstream pool",
    stilling: "stilling basin",
    noControl: "the crest does not control the flow",
    cavitation: "crest pressure below the cavitation limit",
    cycleLabel: "one cycle",
    planView2: "plan view",
    nappeMeet: "nappes meet mid-cycle",
    gateLeaf: "gate leaf",
    venaSection: "vena contracta",
    submergedGate: "gate submerged",
    inletControl: "inlet control",
    outletControl: "outlet control",
    roadLevel: "road surface",
    barrelLabel: "culvert barrel",
    pierLabel: "pier",
    backwaterLabel: "backwater",
    scourLabel: "local scour",
    stoneLayer: "stone layer",
    poolLabel: "pool",
    slotLabel: "vertical slot",
    baffleLabel: "baffle",
    stepLabel: "step",
    restPool: "resting pool",
    axFriction: "darcy friction factor, f",
    axRoughness: "relative roughness, ε/D",
    axHead: "head H, m",
    axDischarge: "discharge Q, m³/s",
    energyLine: "energy line",
    supercritical: "supercritical",
    subcritical: "subcritical",
    jump: "jump",
    noJump: "no jump forms",
    laminar: "laminar",
    criticalZone: "critical zone",
    fullyRough: "fully rough",
    smoothPipe: "smooth pipe",
    pointOffChart: "operating point outside the chart",
    branchSub: "subcritical branch",
    branchSuper: "supercritical branch",
    critical: "critical",
    normal: "normal",
    section: "cross section",
    minEnergy: "E min",
    ratingCurve: "rating curve",
    notch: "notch",
    profile: "water surface profile",
    control: "control section",
    belowRange: "outside valid range",
    elevation: "elevation, m",
    upstream: "upstream",
    downstream: "downstream",
    choked: "choked",
    planView: "plan view",
    slopeBreak: "slope break",
    reachUp: "upstream reach",
    reachDown: "downstream reach",
    uniform: "uniform",
    energyGrade: "energy grade line",
    waterGrade: "water surface line",
    velocityHead: "velocity head",
    datum: "datum",
    lateralInflow: "lateral inflow",
    noInflow: "without the acceleration term",
    momentumEqual: "equal momentum",
    axStation: "distance from the crest, m",
    axFromOrifice: "distance from the orifice plane, m",
    axAlongPipe: "distance along the pipe, m",
    projectile: "projectile path",
    airPocket: "air pocket",
    notAerated: "pocket not vented",
    suction: "nappe drawn to the crest",
    freeNappe: "free nappe",
    notSubmerged: "top lip of the opening above the water surface",
    drownedNappe: "nappe drowned, not a free overfall",
    throat: "throat",
    gauging: "gauging section",
    submerged: "submerged",
    axTime: "time since injection, s",
    axConc: "concentration above background, mg/l",
    axVelocity: "local velocity, m/s",
    axRadius: "distance from the pipe axis, m",
    venaContracta: "vena contracta",
    orifice: "orifice",
    jet: "jet",
    throatSection: "throat",
    pressureTap: "pressure tap",
    stagnation: "stagnation port",
    staticPort: "static port",
    meanVelocity: "mean velocity",
    peak: "peak",
    areaUnder: "area under the curve",
    pressureLine: "pressure head line",
    notVenturi: "not a venturi: throat no narrower than the pipe",
    throatNoControl: "throat does not control the flow, discharge cannot be computed",
    powerLaw: "power law",
    wider: "greater dispersion",
    steadyRate: "constant rate",
    aboveChart: "above the chart",
    noProfile: "profile cannot be computed",
    noNormalDepth: "no normal depth exists",
    rapidlyVaried: "rapidly varied flow",
    profileEnds: "profile ends here",
    collector: "collector channel",
    influenceEnd: "influence down to 1%",
    structure: "structure",
    structureDrowned: "structure drowned, no backwater",
    tailwater: "tailwater",
    drowned: "jump drowned",
    crest: "crest",
    /* keluarga G: air tanah, rembesan, geoteknik */
    axSection: "horizontal distance, m",
    millionCubic: "million m³",
    noRunoff: "this rain produces no runoff",
    wallRoughness: "wall roughness",
    phreaticLine: "phreatic line",
    toeDrain: "toe drain",
    embankment: "embankment body",
    imperviousLabel: "impervious layer",
    seepageFace: "seepage face",
    wellLabel: "well",
    drawdownCone: "drawdown cone",
    staticLevel: "static water level",
    pumpingLevel: "pumping water level",
    aquiferLabel: "aquifer",
    confiningLabel: "confining layer",
    halfDrawdown: "half the drawdown",
    influenceRadius: "radius of influence",
    axWellRadius: "distance from the well axis, m",
    axDrawdown: "drawdown, m",
    axDay: "time, d",
    axWaterTable: "water table, m",
    axRecharge: "recharge, mm/d",
    rechargeCurve: "recharge",
    headCurve: "water table",
    meanLevel: "mean level",
    lagLabel: "peak lag",
    upliftLabel: "uplift",
    resultantLabel: "resultant",
    middleThird: "middle third",
    heelLabel: "heel",
    toeLabelDam: "toe",
    drainLine: "drain line",
    baseStress: "base stress",
    axGrainLog: "grain size, mm",
    axPassing: "passing, %",
    baseSoil: "soil protected",
    filterSoil: "filter",
    filterWindow: "filter window",
    retainLimit: "retention limit",
    drainLimit: "drainage limit",
    axSeepGradient: "hydraulic gradient, i",
    axSeepVelocity: "bulk velocity, m/s",
    darcyLine: "darcy law",
    inertialLine: "inertial limit",
    rockfillLabel: "rockfill",
    axHour: "hour of day, h",
    sleepPressure: "sleep pressure S",
    upperThreshold: "upper threshold",
    lowerThreshold: "lower threshold",
    asleepLabel: "asleep",
    awakeLabel: "awake",
    lyingAwake: "lying awake",
    freeRun: "free running cycle",
  },
} as const;

export type CanvasLabels = (typeof CANVAS)["id"];

export function cl(lang: Lang): CanvasLabels {
  return CANVAS[lang] as CanvasLabels;
}
